DIGITS = "0123456789"
UPPERCASE = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
LOWERCASE = "abcdefghijklmnopqrstuvwxyz"
PUNCTUATION = "!#$%&*+-=?@^_"
ALL_OPTION = DIGITS + UPPERCASE + LOWERCASE + PUNCTUATION

DIGITS_OBJ = "digits"
UPPERCASE_OBJ = "uppercase"
LOWERCASE_OBJ = "lowercase"
PUNCTUATION_OBJ = "symbols"
LONG_OBJ = "long"
